<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use App\Models\KhachHang;
use Carbon\Carbon;

class KhachHangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('khach_hangs')->truncate();
        $khachHang = [
            // Ngày 01/09 có 3 khách
            [
                'ho_va_ten'   => 'Nguyen Van A',
                'email'       => 'a@gmail.com',
                'so_dien_thoai' => '0909123456',
                'password'    => '123456',
                'dia_chi'     => '12 Nguyễn Văn Linh, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '2000-01-01',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-01'),
                'updated_at'  => Carbon::parse('2025-09-01'),
            ],
            [
                'ho_va_ten'   => 'Tran Thi B',
                'email'       => 'b@gmail.com',
                'so_dien_thoai' => '0909987654',
                'password'    => '123456',
                'dia_chi'     => '45 Lê Duẩn, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1999-05-20',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-01'),
                'updated_at'  => Carbon::parse('2025-09-01'),
            ],
            [
                'ho_va_ten'   => 'Le Van C',
                'email'       => 'c@gmail.com',
                'so_dien_thoai' => '0912345678',
                'password'    => '123456',
                'dia_chi'     => '78 Trần Phú, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1998-03-15',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-01'),
                'updated_at'  => Carbon::parse('2025-09-01'),
            ],

            // Ngày 03/09 có 4 khách
            [
                'ho_va_ten'   => 'Pham Thi D',
                'email'       => 'd@gmail.com',
                'so_dien_thoai' => '0978123456',
                'password'    => '123456',
                'dia_chi'     => '22 Ông Ích Khiêm, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1997-07-22',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-03'),
                'updated_at'  => Carbon::parse('2025-09-03'),
            ],
            [
                'ho_va_ten'   => 'Hoang Van E',
                'email'       => 'e@gmail.com',
                'so_dien_thoai' => '0969123456',
                'password'    => '123456',
                'dia_chi'     => '305 Điện Biên Phủ, Thanh Khê, Đà Nẵng',
                'ngay_sinh'   => '1995-12-05',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-03'),
                'updated_at'  => Carbon::parse('2025-09-03'),
            ],
            [
                'ho_va_ten'   => 'Vu Thi F',
                'email'       => 'f@gmail.com',
                'so_dien_thoai' => '0932123456',
                'password'    => '123456',
                'dia_chi'     => '150 Nguyễn Hoàng, Thanh Khê, Đà Nẵng',
                'ngay_sinh'   => '2001-04-10',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-03'),
                'updated_at'  => Carbon::parse('2025-09-03'),
            ],
            [
                'ho_va_ten'   => 'Do Van G',
                'email'       => 'g@gmail.com',
                'so_dien_thoai' => '0923123456',
                'password'    => '123456',
                'dia_chi'     => '88 Nguyễn Hữu Thọ, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1996-08-30',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-03'),
                'updated_at'  => Carbon::parse('2025-09-03'),
            ],

            // Ngày 05/09 có 3 khách
            [
                'ho_va_ten'   => 'Nguyen Thi H',
                'email'       => 'h@gmail.com',
                'so_dien_thoai' => '0911123456',
                'password'    => '123456',
                'dia_chi'     => '12 Hoàng Diệu, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '2002-11-02',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-05'),
                'updated_at'  => Carbon::parse('2025-09-05'),
            ],
            [
                'ho_va_ten'   => 'Truong Van I',
                'email'       => 'i@gmail.com',
                'so_dien_thoai' => '0987654321',
                'password'    => '123456',
                'dia_chi'     => '5 Trưng Nữ Vương, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1994-09-09',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-05'),
                'updated_at'  => Carbon::parse('2025-09-05'),
            ],
            [
                'ho_va_ten'   => 'Bui Thi J',
                'email'       => 'j@gmail.com',
                'so_dien_thoai' => '0956123456',
                'password'    => '123456',
                'dia_chi'     => '40 Phan Châu Trinh, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1993-06-12',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-05'),
                'updated_at'  => Carbon::parse('2025-09-05'),
            ],
            [
                'ho_va_ten'   => 'Pham Van K',
                'email'       => 'k@gmail.com',
                'so_dien_thoai' => '0913000001',
                'password'    => '123456',
                'dia_chi'     => '123 Nguyễn Văn Linh, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1992-02-10',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-20'),
                'updated_at'  => Carbon::parse('2025-09-20'),
            ],
            [
                'ho_va_ten'   => 'Nguyen Thi L',
                'email'       => 'l@gmail.com',
                'so_dien_thoai' => '0913000002',
                'password'    => '123456',
                'dia_chi'     => '55 Lê Lợi, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1991-03-22',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-20'),
                'updated_at'  => Carbon::parse('2025-09-20'),
            ],
            [
                'ho_va_ten'   => 'Tran Van M',
                'email'       => 'm@gmail.com',
                'so_dien_thoai' => '0913000003',
                'password'    => '123456',
                'dia_chi'     => '88 Nguyễn Trãi, Thanh Khê, Đà Nẵng',
                'ngay_sinh'   => '1990-06-14',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-22'),
                'updated_at'  => Carbon::parse('2025-09-22'),
            ],
            [
                'ho_va_ten'   => 'Le Thi N',
                'email'       => 'n@gmail.com',
                'so_dien_thoai' => '0913000004',
                'password'    => '123456',
                'dia_chi'     => '12 Nguyễn Tri Phương, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1994-07-07',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-23'),
                'updated_at'  => Carbon::parse('2025-09-23'),
            ],
            [
                'ho_va_ten'   => 'Hoang Van O',
                'email'       => 'o@gmail.com',
                'so_dien_thoai' => '0913000005',
                'password'    => '123456',
                'dia_chi'     => '60 Hùng Vương, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1997-05-17',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-25'),
                'updated_at'  => Carbon::parse('2025-09-25'),
            ],
            [
                'ho_va_ten'   => 'Vu Thi P',
                'email'       => 'p@gmail.com',
                'so_dien_thoai' => '0913000006',
                'password'    => '123456',
                'dia_chi'     => '77 Nguyễn Hoàng, Thanh Khê, Đà Nẵng',
                'ngay_sinh'   => '1995-08-19',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-25'),
                'updated_at'  => Carbon::parse('2025-09-25'),
            ],
            [
                'ho_va_ten'   => 'Pham Van Q',
                'email'       => 'q@gmail.com',
                'so_dien_thoai' => '0913000007',
                'password'    => '123456',
                'dia_chi'     => '90 Nguyễn Du, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1989-01-05',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-09-28'),
                'updated_at'  => Carbon::parse('2025-09-28'),
            ],
            [
                'ho_va_ten'   => 'Nguyen Thi R',
                'email'       => 'r@gmail.com',
                'so_dien_thoai' => '0913000008',
                'password'    => '123456',
                'dia_chi'     => '15 Trần Quốc Toản, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '2000-10-10',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-10-01'),
                'updated_at'  => Carbon::parse('2025-10-01'),
            ],
            [
                'ho_va_ten'   => 'Tran Van S',
                'email'       => 's@gmail.com',
                'so_dien_thoai' => '0913000009',
                'password'    => '123456',
                'dia_chi'     => '120 Lê Duẩn, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1998-04-04',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-10-01'),
                'updated_at'  => Carbon::parse('2025-10-01'),
            ],
            [
                'ho_va_ten'   => 'Le Van T',
                'email'       => 't@gmail.com',
                'so_dien_thoai' => '0913000010',
                'password'    => '123456',
                'dia_chi'     => '34 Trưng Nữ Vương, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1992-11-11',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-10-03'),
                'updated_at'  => Carbon::parse('2025-10-03'),
            ],
            [
                'ho_va_ten'   => 'Hoang Thi U',
                'email'       => 'u@gmail.com',
                'so_dien_thoai' => '0913000011',
                'password'    => '123456',
                'dia_chi'     => '210 Nguyễn Văn Thoại, Sơn Trà, Đà Nẵng',
                'ngay_sinh'   => '1991-09-09',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-10-05'),
                'updated_at'  => Carbon::parse('2025-10-05'),
            ],
            [
                'ho_va_ten'   => 'Pham Van V',
                'email'       => 'v@gmail.com',
                'so_dien_thoai' => '0913000012',
                'password'    => '123456',
                'dia_chi'     => '50 Nguyễn Hữu Thọ, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1996-06-06',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-10-10'),
                'updated_at'  => Carbon::parse('2025-10-10'),
            ],
            [
                'ho_va_ten'   => 'Nguyen Van W',
                'email'       => 'w@gmail.com',
                'so_dien_thoai' => '0913000013',
                'password'    => '123456',
                'dia_chi'     => '88 Hoàng Diệu, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1999-12-12',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-10-15'),
                'updated_at'  => Carbon::parse('2025-10-15'),
            ],
            [
                'ho_va_ten'   => 'Tran Thi X',
                'email'       => 'x@gmail.com',
                'so_dien_thoai' => '0913000014',
                'password'    => '123456',
                'dia_chi'     => '99 Phan Chu Trinh, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '2000-08-18',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-10-20'),
                'updated_at'  => Carbon::parse('2025-10-20'),
            ],
            [
                'ho_va_ten'   => 'Bui Van Y',
                'email'       => 'y@gmail.com',
                'so_dien_thoai' => '0913000015',
                'password'    => '123456',
                'dia_chi'     => '12 Pasteur, Hải Châu, Đà Nẵng',
                'ngay_sinh'   => '1995-05-25',
                'avatar'      => null,
                'hash_reset'  => null,
                'hash_active' => null,
                'is_active'   => true,
                'is_block'    => false,
                'created_at'  => Carbon::parse('2025-10-31'),
                'updated_at'  => Carbon::parse('2025-10-31'),
            ],
            // ===== THÁNG 11/2025 =====
            [
                'ho_va_ten' => 'Nguyen Van AA',
                'email' => 'aa@gmail.com',
                'so_dien_thoai' => '0914000001',
                'password' => '123456',
                'dia_chi' => 'Hải Châu, Đà Nẵng',
                'ngay_sinh' => '1996-01-10',
                'avatar' => null,
                'hash_reset' => null,
                'hash_active' => null,
                'is_active' => true,
                'is_block' => false,
                'created_at' => Carbon::parse('2025-11-02'),
                'updated_at' => Carbon::parse('2025-11-02'),
            ],
            [
                'ho_va_ten' => 'Tran Thi BB',
                'email' => 'bb@gmail.com',
                'so_dien_thoai' => '0914000002',
                'password' => '123456',
                'dia_chi' => 'Thanh Khê, Đà Nẵng',
                'ngay_sinh' => '1998-05-12',
                'avatar' => null,
                'hash_reset' => null,
                'hash_active' => null,
                'is_active' => true,
                'is_block' => false,
                'created_at' => Carbon::parse('2025-11-05'),
                'updated_at' => Carbon::parse('2025-11-05'),
            ],
            [
                'ho_va_ten' => 'Le Van CC',
                'email' => 'cc@gmail.com',
                'so_dien_thoai' => '0914000003',
                'password' => '123456',
                'dia_chi' => 'Sơn Trà, Đà Nẵng',
                'ngay_sinh' => '1994-03-20',
                'avatar' => null,
                'hash_reset' => null,
                'hash_active' => null,
                'is_active' => true,
                'is_block' => false,
                'created_at' => Carbon::parse('2025-11-10'),
                'updated_at' => Carbon::parse('2025-11-10'),
            ],
            // ===== THÁNG 12/2025 =====
            [
                'ho_va_ten' => 'Pham Thi DD',
                'email' => 'dd@gmail.com',
                'so_dien_thoai' => '0914000004',
                'password' => '123456',
                'dia_chi' => 'Liên Chiểu, Đà Nẵng',
                'ngay_sinh' => '1999-07-07',
                'avatar' => null,
                'hash_reset' => null,
                'hash_active' => null,
                'is_active' => true,
                'is_block' => false,
                'created_at' => Carbon::parse('2025-12-01'),
                'updated_at' => Carbon::parse('2025-12-01'),
            ],
            [
                'ho_va_ten' => 'Hoang Van EE',
                'email' => 'ee@gmail.com',
                'so_dien_thoai' => '0914000005',
                'password' => '123456',
                'dia_chi' => 'Hải Châu, Đà Nẵng',
                'ngay_sinh' => '1992-11-11',
                'avatar' => null,
                'hash_reset' => null,
                'hash_active' => null,
                'is_active' => true,
                'is_block' => false,
                'created_at' => Carbon::parse('2025-12-10'),
                'updated_at' => Carbon::parse('2025-12-10'),
            ],
            [
                'ho_va_ten' => 'Nguyen Thi FF',
                'email' => 'ff@gmail.com',
                'so_dien_thoai' => '0914000006',
                'password' => '123456',
                'dia_chi' => 'Cẩm Lệ, Đà Nẵng',
                'ngay_sinh' => '2000-09-09',
                'avatar' => null,
                'hash_reset' => null,
                'hash_active' => null,
                'is_active' => true,
                'is_block' => false,
                'created_at' => Carbon::parse('2025-12-18'),
                'updated_at' => Carbon::parse('2025-12-18'),
            ],

        ];

        foreach ($khachHang as &$item) {
            $item['avatar'] = 'https://dimensions.edu.vn/public/upload/2025/01/avatar-meo-vo-tri-10.webp';
            $item['password'] = Hash::make($item['password']);
        }
        // 🔹 Chèn dữ liệu mới
        DB::table('khach_hangs')->insert($khachHang);
    }
}
