<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class NhanVienSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('nhan_viens')->insert([
            [
                'email' => 'admin@greenmart.com',
                'ho_va_ten' => 'Admin GreenMart',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000001',
                'ngay_sinh' => '1990-01-01',
                'dia_chi' => 'Đà Nẵng',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 1,
            ],
            [
                'email' => 'nhanvien@greenmart.com',
                'ho_va_ten' => 'Nhân viên Bán Hàng',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000002',
                'ngay_sinh' => '1995-05-05',
                'dia_chi' => 'Đà Nẵng',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 2,
            ],

            // 13 nhân viên thêm
            [
                'email' => 'nguyen.an@greenmart.com',
                'ho_va_ten' => 'Nguyễn Văn An',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000003',
                'ngay_sinh' => '1993-03-21',
                'dia_chi' => 'Hà Nội',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 2,
            ],
            [
                'email' => 'tran.binh@greenmart.com',
                'ho_va_ten' => 'Trần Quốc Bình',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000004',
                'ngay_sinh' => '1994-11-12',
                'dia_chi' => 'Hồ Chí Minh',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 2,
            ],
            [
                'email' => 'le.chau@greenmart.com',
                'ho_va_ten' => 'Lê Hải Châu',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000005',
                'ngay_sinh' => '1992-06-19',
                'dia_chi' => 'Đà Nẵng',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 2,
            ],
            [
                'email' => 'pham.duy@greenmart.com',
                'ho_va_ten' => 'Phạm Đức Duy',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000006',
                'ngay_sinh' => '1996-10-02',
                'dia_chi' => 'Quảng Nam',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 2,
            ],
            [
                'email' => 'hoang.hoa@greenmart.com',
                'ho_va_ten' => 'Hoàng Thu Hoa',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000007',
                'ngay_sinh' => '1997-02-15',
                'dia_chi' => 'Huế',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 2,
            ],
            [
                'email' => 'vo.khanh@greenmart.com',
                'ho_va_ten' => 'Võ Minh Khánh',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000008',
                'ngay_sinh' => '1991-07-17',
                'dia_chi' => 'Hải Phòng',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 2,
            ],
            [
                'email' => 'dang.lan@greenmart.com',
                'ho_va_ten' => 'Đặng Ngọc Lan',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000009',
                'ngay_sinh' => '1998-04-24',
                'dia_chi' => 'Nha Trang',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 2,
            ],
            [
                'email' => 'bui.minh@greenmart.com',
                'ho_va_ten' => 'Bùi Văn Minh',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000010',
                'ngay_sinh' => '1990-09-09',
                'dia_chi' => 'Cần Thơ',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 3,
            ],
            [
                'email' => 'ngo.ngoc@greenmart.com',
                'ho_va_ten' => 'Ngô Ngọc Quỳnh',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000011',
                'ngay_sinh' => '1993-12-11',
                'dia_chi' => 'Đồng Nai',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 2,
            ],
            [
                'email' => 'huynh.son@greenmart.com',
                'ho_va_ten' => 'Huỳnh Trọng Sơn',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000012',
                'ngay_sinh' => '1995-03-03',
                'dia_chi' => 'Bình Dương',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 2,
            ],
            [
                'email' => 'do.tam@greenmart.com',
                'ho_va_ten' => 'Đỗ Văn Tâm',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000013',
                'ngay_sinh' => '1994-08-14',
                'dia_chi' => 'Hà Tĩnh',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 3,
            ],
            [
                'email' => 'ly.trang@greenmart.com',
                'ho_va_ten' => 'Lý Mỹ Trang',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000014',
                'ngay_sinh' => '1997-01-27',
                'dia_chi' => 'Đà Lạt',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 2,
            ],
            [
                'email' => 'truong.vi@greenmart.com',
                'ho_va_ten' => 'Trương Bảo Vi',
                'password' => Hash::make('123456'),
                'so_dien_thoai' => '0900000015',
                'ngay_sinh' => '1996-06-06',
                'dia_chi' => 'Quảng Bình',
                'tinh_trang' => 1,
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMzLxoBuDxx4WHiQiV0TvrKDC2L-7AafwIWg&s',
                'id_chuc_vu' => 2,
            ],
        ]);
    }
}
